---
- name: create tls directory structure
  sudo: yes
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0700
  tags:
    - nginx

- name: create tls files
  sudo: yes
  command: /usr/local/bin/generate_certificate --location '*.service.{{ consul_dns_domain }}' --prefix nginx --destination /etc/nginx/ssl --dns '*.service.{{ consul_dns_domain }}'
  args:
    creates: /etc/nginx/ssl/nginx.key
  tags:
    - nginx

- name: encrypt admin password
  sudo: yes
  shell: htpasswd -Bnb admin {{ nginx_admin_password }} | cut -f 2 -d ':'
  register: nginx_admin_password_encrypted
  changed_when: no

- name: set admin password variable
  set_fact:
    nginx_admin_password_encrypted: "{{ nginx_admin_password_encrypted.stdout }}"

- include: distributive.yml
