---
- name: install vault
  sudo: yes
  yum:
    name: "https://bintray.com/artifact/download/ciscocloud/rpm/vault-0.1.2-1.el7.centos.x86_64.rpm"
    state: present
  tags:
    - vault
    - bootstrap

- name: deploy tls files
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest}}"
  with_items:
    - src: ssl/certs/vault.cert.pem
      dest: /etc/vault/ssl/vault.cert
    - src: ssl/private/vault.key.pem
      dest: /etc/vault/ssl/vault.key
  notify:
    - restart vault
  tags:
    - vault

- name: configure vault
  sudo: yes
  template:
    src: vault.config.j2
    dest: /etc/vault/vault.config
  notify:
    - restart vault
  tags:
    - vault

- name: enable vault
  sudo: yes
  service:
    name: vault
    enabled: yes
    state: started
  tags: 
    - vault

- name: register vault service
  sudo: yes
  command: /usr/local/bin/vault-register-with-consul.sh
  tags:
    - vault

- name: bootstrap vault
  sudo: yes
  command: /usr/local/bin/vault-bootstrap.sh
  notify:
    - restart vault
  tags:
    - vault

- meta: flush_handlers
