---
- name: create zookeeper acl
  sudo: yes
  command: "{{ chronos_zk_acl_cmd }}"
  notify:
    - restart chronos
  when: zk_chronos_user_secret is defined
  run_once: true
  tags:
    - chronos

- name: create chronos conf directory
  sudo: yes
  file:
    dest: /etc/chronos/conf
    state: directory
  tags:
    - chronos

- include: framework_auth.yml

- name: set key/value options
  sudo: yes
  when: item.value != ""
  copy:
    dest: /etc/chronos/conf/{{ item.key }}
    content: "{{ item.value }}"
  with_items:
    - key: zk
      value: "{{ chronos_zk_connect }}"
    - key: ssl_keystore_password
      value: "{{ chronos_keystore_password }}"
    - key: http_port
      value: 18080
    - key: event_subscriber
      value: http_callback
  notify:
    - restart chronos
  tags:
    - chronos

- name: check keystore consistency
  fail: msg="cannot set keystore path without keystore password"
  when: chronos_keystore_path != "" and chronos_keystore_password == ""

- name: copy ssl keystore
  when: chronos_keystore_path != ""
  sudo: yes
  copy:
    src: "{{ chronos_keystore_path }}"
    dest: /etc/chronos/keystore.jks
  notify:
    - restart chronos
  tags:
    - chronos

- name: create chronos_keystore_path
  when: chronos_keystore_path != ""
  sudo: yes
  copy:
    dest: /etc/chronos/conf/ssl_keystore_path
    content: /etc/chronos/keystore.jks
  notify:
    - restart chronos
  tags:
    - chronos

# since the Mesosphere chronos package configures itself with files
# in a directory, we need to clean up old options when they become
# unset.
- name: remove blank options
  sudo: yes
  when: item.value == ""
  file:
    dest: /etc/chronos/conf/{{ item.key }}
    state: absent
    mode: 0700
  with_items:
    - key: http_credentials
      value: "{{ chronos_http_credentials }}"
    - key: ssl_keystore_password
      value: "{{ chronos_keystore_password }}"
    - key: ssl_keystore_path
      value: "{{ chronos_keystore_path }}"
  notify:
    - restart chronos
  tags:
    - chronos

- name: remove ssl keystore
  when: chronos_keystore_path == ""
  sudo: yes
  file:
    dest: /etc/chronos/keystore.jks
    state: absent
  tags:
    - chronos
