---
- name: add mesosphere repository
  sudo: yes
  yum:
    name:  http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    state: present
  tags:
    - chronos

- name: install chronos package
  sudo: yes
  yum:
    name: chronos
    state: present
  tags:
    - chronos

- include: conf.yml

- name: configure chronos unit file
  sudo: yes
  replace:
    dest: /usr/lib/systemd/system/chronos.service
    regexp: "=network.target"
    replace: '=mesos-master.service'
  notify:
    - reload chronos
    - restart chronos
  tags:
    - chronos

- name: enable and start chronos
  sudo: yes
  service:
    enabled: yes
    name: chronos
    state: started
  tags:
    - chronos

- meta: flush_handlers

- include: nginx-proxy.yml

- name: deploy iptables configuration
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: chronos-consul.cfg
      dest: /etc/consul-template/config.d
  notify:
    - reload consul-template
  tags:
    - chronos

- name: deploy iptables template
  sudo: yes
  template:
    src: chronos-iptables.tmpl.j2
    dest: /etc/consul-template/templates/chronos-iptables.tmpl
  notify:
    - reload consul-template
  tags:
    - chronos

- name: ensure consul.d is present
  sudo: yes
  file:
    path: "{{ consul_dir }}"
    state: directory
  tags:
    - chronos

- name: generate chronos consul service
  sudo: yes
  template:
    src: chronos-consul.j2
    dest: "{{ consul_dir }}/chronos.json"
  notify:
    - reload consul
  tags:
    - chronos
