---
- name: Configure Hadoop HDFS NameNode
  sudo: yes
  template: src={{ item }}.xml.j2 dest={{ hdfs_conf_dir }}/{{ item | replace("namenode-", "") }}.xml
  with_items:
    - core-site
    - namenode-hdfs-site
  notify:
    - Restart Hadoop HDFS NameNode
  tags:
    - hdfs

- name: Downloading pub key
  fetch: 
    src: "/home/hdfs/.ssh/id_rsa.pub"
    dest: "/tmp/id_rsa.pub"
    flat: yes
  register: fetch_public_key
  tags:
    - hdfs

- name: Create Hadoop HDFS NameNode data directories
  sudo: true
  file: 
    path: "/dfs/nn"
    owner: hdfs
    group: hdfs
    state: directory
  register: created_hdfs_namenode_data_dir
  tags:
    - hdfs

- name: Format HDFS NameNode data directories
  sudo_user: hdfs
  sudo: true
  shell: source /etc/profile.d/hadoop.sh; hdfs namenode -format
  when: created_hdfs_namenode_data_dir | changed
  tags:
    - hdfs

- name: Stop HDFS NameNode 
  sudo_user: hdfs
  sudo: true
  shell: source /etc/profile.d/hadoop.sh; hadoop-daemon.sh stop namenode
  ignore_errors: True
  tags:
    - hdfs

- name: Enable and start the Hadoop HDFS NameNode service
#  service: name=hadoop-hdfs-namenode enabled=yes state=started
  sudo_user: hdfs
  sudo: true
  shell: source /etc/profile.d/hadoop.sh; hadoop-daemon.sh start namenode
  tags:
    - hdfs
